# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
    #- run: npm ci
    - run: |
        npm install
        npm run build --if-present
    - name: Persist to workspace
      uses: actions/upload-artifact@v2
      with:
        name: workspace
        path: public/

  test:
    needs: build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os: [ubuntu-latest,windows-2016]
        node-version: [12.x, 14.x]
    steps:
    - name: Attatch to workspace
      uses: actions/checkout@v2
      with:
        name: workspace
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: npm install and test
      run: |
        npm install
        npm test
      env:
        CI: true
